#ifndef BASE_H
#define BASE_H

#include "base_cfg.h"

#if USE_SDL2 == 1
#   include "functions/sdlinclude.h"
#endif

#include "3rdp/ustring.h"
#include "functions/defs.h"
#include "functions/debug.h"
#include "functions/profiling.h"
#include "functions/meta.h"
#include "functions/enum.h"
#include "functions/ssu.h"
#include "functions/sort_utils.h"
#include "functions/random.h"
#include "functions/common.h"
#include "functions/hash.h"
#include "functions/emsc_utils.h"
#include "types/containers/fast_vector.h"
#include "types/containers/TightPool.h"
#include "types/containers/Pool.h"
#include "types/containers/Array.h"
#include "types/containers/VArray.h"
#include "types/containers/SortedArray.h"
#include "types/containers/SharedBuffer.h"
#include "types/containers/RoundBuffer.h"
#include "types/containers/HashMap.h"
#include "types/containers/HashSet.h"
#include "types/containers/CompsPool.h"
#include "types/containers/PolyPool.h"
#include "types/containers/Items.h"
#include "types/containers/Items2.h"
#include "types/containers/ChunkedBuffer.h"
#include "types/containers/ItemPtr.h"
#include "types/containers/ItemAutoPtr.h"
#include "types/containers/ItemRefPtr.h"
#include "types/BitScanner.h"
#include "types/Bits.h"
#include "types/TestBench.h"
#include "types/SimpleFont.h"
#include "types/CommonPtr.h"
#include "types/Exception.h"
#include "types/RefCommonPtr.h"
#include "types/RefCount.h"
#include "types/RefPtr.h"
#include "types/Type.h"
#include "types/TypesPack.h"
#include "types/TypesCombiner.h"
#include "types/Mask.h"
#include "types/Timer.h"
#include "types/BlockMeasure.h"
#include "types/Variant.h"
#include "types/VariantTypesLooper.h"
#include "types/Call.h"
#include "types/Manager.h"
#include "types/Path.h"
#include "types/FileLister.h"
#include "types/Config.h"
#include "types/OptionsHandler.h"
#include "types/Singleton.h"
#include "types/EventsHandler.h"
#include "types/EventsReciever.h"
#include "types/ObjFunc.h"
#include "types/TypedFuncs.h"

#endif //BASE_H
